packages:
  - benchmarks/charts
  - benchmarks/dashboard/*
  - benchmarks/deep-tree/*
  - docs/*
  - examples/apps/*
  - examples/games/*
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
