packages:
  - benchmarks/charts
  - benchmarks/dashboard/*
  - benchmarks/deep-tree/*
  - docs/*
  - examples/apps/*
  - examples/games/*
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  vue-demi: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
