packages:
  - benchmarks/charts
  - benchmarks/dashboard/*
  - benchmarks/deep-tree/*
  - docs/*
  - examples/apps/*
  - examples/games/*
  - examples/its
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  esbuild: true
  sharp: true
  vue-demi: true

minimumReleaseAgeExclude:
  - "@storybook/addon-a11y@10.5.6"
  - "@storybook/addon-docs@10.5.6"
  - "@storybook/addon-vitest@10.5.6"
  - "@storybook/builder-vite@10.5.6"
  - "@storybook/csf-plugin@10.5.6"
  - "@storybook/react-dom-shim@10.5.6"
  - "@storybook/react-vite@10.5.6"
  - "@storybook/react@10.5.6"
  - "@storybook/web-components-vite@10.5.6"
  - "@storybook/web-components@10.5.6"
  - eslint-plugin-storybook@10.5.6
  - storybook@10.5.6

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
