import { html } from "@inglorious/web"

export const About = {
  click(entity) {
    entity.name += "!"
  },

  render(entity, api) {
    return html`
      <div>
        <h1>
          About
          <span @click=${() => api.notify(`#${entity.id}:click`)}
            >${entity.name}</span
          >
        </h1>
        <p>This is a static page generated by SSX.</p>
        <a href="/">Back Home</a>
      </div>
    `
  },
}

export const metadata = {
  title: "About",
}
