export const statCards = [
  {
    id: "users",
    label: "Users",
    value: "26K",
    change: "-12.4%",
    direction: "arrow_downward",
    className: "iw-dashboard-stat-primary",
    chartType: "line",
    data: [65, 59, 84, 84, 51, 55, 40],
  },
  {
    id: "income",
    label: "Income",
    value: "$6.2K",
    change: "40.9%",
    direction: "arrow_upward",
    className: "iw-dashboard-stat-info",
    chartType: "line",
    hasDots: true,
    data: [1, 18, 9, 17, 34, 22, 11],
  },
  {
    id: "conversionRate",
    label: "Conversion Rate",
    value: "2.49%",
    change: "84.7%",
    direction: "arrow_upward",
    className: "iw-dashboard-stat-warning",
    chartType: "area",
    data: [78, 81, 80, 45, 34, 12, 40],
  },
  {
    id: "sessions",
    label: "Sessions",
    value: "44K",
    change: "-23.6%",
    direction: "arrow_downward",
    className: "iw-dashboard-stat-danger",
    chartType: "bar",
    data: [78, 81, 80, 45, 34, 12, 40, 85, 65, 23, 12, 98, 34, 84, 67, 82],
  },
]

export const trafficSeries = [
  { month: "Jan", visits: 132, unique: 62 },
  { month: "Feb", visits: 96, unique: 101 },
  { month: "Mar", visits: 147, unique: 110 },
  { month: "Apr", visits: 131, unique: 112 },
  { month: "May", visits: 170, unique: 133 },
  { month: "Jun", visits: 51, unique: 88 },
  { month: "Jul", visits: 142, unique: 145 },
]

export const trafficSummary = [
  {
    label: "Visits",
    value: "29.703 Users (40%)",
    progress: 40,
    color: "success",
  },
  {
    label: "Unique",
    value: "24.093 Users (20%)",
    progress: 20,
    color: "info",
  },
  {
    label: "Pageviews",
    value: "78.706 Views (60%)",
    progress: 60,
    color: "warning",
  },
  {
    label: "New Users",
    value: "22.123 Users (80%)",
    progress: 80,
    color: "error",
  },
  // { label: "Bounce Rate", value: "40.15%", progress: 40, color: "primary" },
]

export const socialCards = [
  {
    icon: "thumb_up",
    capClass: "iw-dashboard-social-cap-facebook",
    top: "89k",
    bottom: "459",
    topLabel: "friends",
    bottomLabel: "feeds",
    data: [24, 28, 20, 30, 26, 34, 29],
  },
  {
    icon: "alternate_email",
    capClass: "iw-dashboard-social-cap-twitter",
    top: "973k",
    bottom: "1.792",
    topLabel: "followers",
    bottomLabel: "tweets",
    data: [12, 19, 16, 22, 24, 28, 32],
  },
  {
    icon: "work",
    capClass: "iw-dashboard-social-cap-linkedin",
    top: "500+",
    bottom: "292",
    topLabel: "contacts",
    bottomLabel: "feeds",
    data: [9, 12, 10, 14, 13, 17, 16],
  },
]

export const clientBars = [
  ["Monday", 34, 78],
  ["Tuesday", 56, 94],
  ["Wednesday", 12, 67],
  ["Thursday", 43, 91],
  ["Friday", 22, 73],
  ["Saturday", 53, 82],
  ["Sunday", 9, 69],
]

export const sourceBars = [
  ["Male", 43, "person", "warning", "", ""],
  ["Female", 37, "person_2", "warning", "", ""],
  ["Organic Search", 56, "travel_explore", "success", "191.235", "(56%)"],
  ["Facebook", 15, "public", "success", "51.223", "(15%)"],
  ["Twitter", 11, "tag", "success", "37.564", "(11%)"],
  ["LinkedIn", 8, "business_center", "success", "27.319", "(8%)"],
]

export const userRows = [
  {
    id: 1,
    name: "Yiorgos Avraamu",
    subtitle: "New | Registered: Jan 1, 2023",
    initials: "YA",
    country: "US",
    usage: 50,
    range: "Jun 11, 2023 - Jul 10, 2023",
    payment: "Mastercard",
    activity: "10 sec ago",
    status: "success",
  },
  {
    id: 2,
    name: "Avram Tarasios",
    subtitle: "Recurring | Registered: Jan 1, 2023",
    initials: "AT",
    country: "BR",
    usage: 10,
    range: "Jun 11, 2023 - Jul 10, 2023",
    payment: "Visa",
    activity: "5 minutes ago",
    status: "error",
  },
  {
    id: 3,
    name: "Quintin Ed",
    subtitle: "New | Registered: Jan 1, 2023",
    initials: "QE",
    country: "IN",
    usage: 74,
    range: "Jun 11, 2023 - Jul 10, 2023",
    payment: "Stripe",
    activity: "1 hour ago",
    status: "warning",
  },
  {
    id: 4,
    name: "Eneas Kwadwo",
    subtitle: "New | Registered: Jan 1, 2023",
    initials: "EK",
    country: "FR",
    usage: 98,
    range: "Jun 11, 2023 - Jul 10, 2023",
    payment: "PayPal",
    activity: "Last month",
    status: "secondary",
  },
]
